// The user should define these in keymap.c
#ifndef CATPPUCCIN_FLAVOR
#define CATPPUCCIN_FLAVOR MOCHA
#endif

#ifndef CATPPUCCIN_ACCENT
#define CATPPUCCIN_ACCENT MAUVE
#endif

// Internal helper macros to help with concatenation and recursive evaluation of macros
#define __CTP_CONCAT_(a, b) a##b
#define __CTP_CONCAT(a, b) __CTP_CONCAT_(a, b)
#define __CTP_CONCAT3_(a, b, c) a##b##c
#define __CTP_CONCAT3(a, b, c) __CTP_CONCAT3_(a, b, c)
  
#define RGB_CATPPUCCIN_LATTE_ROSEWATER 0xDC, 0x8A, 0x78
#define RGB_CATPPUCCIN_LATTE_FLAMINGO 0xDD, 0x78, 0x78
#define RGB_CATPPUCCIN_LATTE_PINK 0xEA, 0x76, 0xCB
#define RGB_CATPPUCCIN_LATTE_MAUVE 0x88, 0x39, 0xEF
#define RGB_CATPPUCCIN_LATTE_RED 0xD2, 0x0F, 0x39
#define RGB_CATPPUCCIN_LATTE_MAROON 0xE6, 0x45, 0x53
#define RGB_CATPPUCCIN_LATTE_PEACH 0xFE, 0x64, 0x0B
#define RGB_CATPPUCCIN_LATTE_YELLOW 0xDF, 0x8E, 0x1D
#define RGB_CATPPUCCIN_LATTE_GREEN 0x40, 0xA0, 0x2B
#define RGB_CATPPUCCIN_LATTE_TEAL 0x17, 0x92, 0x99
#define RGB_CATPPUCCIN_LATTE_SKY 0x04, 0xA5, 0xE5
#define RGB_CATPPUCCIN_LATTE_SAPPHIRE 0x20, 0x9F, 0xB5
#define RGB_CATPPUCCIN_LATTE_BLUE 0x1E, 0x66, 0xF5
#define RGB_CATPPUCCIN_LATTE_LAVENDER 0x72, 0x87, 0xFD
#define RGB_CATPPUCCIN_LATTE_TEXT 0x4C, 0x4F, 0x69
#define RGB_CATPPUCCIN_LATTE_SUBTEXT1 0x5C, 0x5F, 0x77
#define RGB_CATPPUCCIN_LATTE_SUBTEXT0 0x6C, 0x6F, 0x85
#define RGB_CATPPUCCIN_LATTE_OVERLAY2 0x7C, 0x7F, 0x93
#define RGB_CATPPUCCIN_LATTE_OVERLAY1 0x8C, 0x8F, 0xA1
#define RGB_CATPPUCCIN_LATTE_OVERLAY0 0x9C, 0xA0, 0xB0
#define RGB_CATPPUCCIN_LATTE_SURFACE2 0xAC, 0xB0, 0xBE
#define RGB_CATPPUCCIN_LATTE_SURFACE1 0xBC, 0xC0, 0xCC
#define RGB_CATPPUCCIN_LATTE_SURFACE0 0xCC, 0xD0, 0xDA
#define RGB_CATPPUCCIN_LATTE_BASE 0xEF, 0xF1, 0xF5
#define RGB_CATPPUCCIN_LATTE_MANTLE 0xE6, 0xE9, 0xEF
#define RGB_CATPPUCCIN_LATTE_CRUST 0xDC, 0xE0, 0xE8
#define RGB_CATPPUCCIN_LATTE_ACCENT __CTP_CONCAT(RGB_CATPPUCCIN_LATTE_, CATPPUCCIN_ACCENT)
  
#define RGB_CATPPUCCIN_FRAPPE_ROSEWATER 0xF2, 0xD5, 0xCF
#define RGB_CATPPUCCIN_FRAPPE_FLAMINGO 0xEE, 0xBE, 0xBE
#define RGB_CATPPUCCIN_FRAPPE_PINK 0xF4, 0xB8, 0xE4
#define RGB_CATPPUCCIN_FRAPPE_MAUVE 0xCA, 0x9E, 0xE6
#define RGB_CATPPUCCIN_FRAPPE_RED 0xE7, 0x82, 0x84
#define RGB_CATPPUCCIN_FRAPPE_MAROON 0xEA, 0x99, 0x9C
#define RGB_CATPPUCCIN_FRAPPE_PEACH 0xEF, 0x9F, 0x76
#define RGB_CATPPUCCIN_FRAPPE_YELLOW 0xE5, 0xC8, 0x90
#define RGB_CATPPUCCIN_FRAPPE_GREEN 0xA6, 0xD1, 0x89
#define RGB_CATPPUCCIN_FRAPPE_TEAL 0x81, 0xC8, 0xBE
#define RGB_CATPPUCCIN_FRAPPE_SKY 0x99, 0xD1, 0xDB
#define RGB_CATPPUCCIN_FRAPPE_SAPPHIRE 0x85, 0xC1, 0xDC
#define RGB_CATPPUCCIN_FRAPPE_BLUE 0x8C, 0xAA, 0xEE
#define RGB_CATPPUCCIN_FRAPPE_LAVENDER 0xBA, 0xBB, 0xF1
#define RGB_CATPPUCCIN_FRAPPE_TEXT 0xC6, 0xD0, 0xF5
#define RGB_CATPPUCCIN_FRAPPE_SUBTEXT1 0xB5, 0xBF, 0xE2
#define RGB_CATPPUCCIN_FRAPPE_SUBTEXT0 0xA5, 0xAD, 0xCE
#define RGB_CATPPUCCIN_FRAPPE_OVERLAY2 0x94, 0x9C, 0xBB
#define RGB_CATPPUCCIN_FRAPPE_OVERLAY1 0x83, 0x8B, 0xA7
#define RGB_CATPPUCCIN_FRAPPE_OVERLAY0 0x73, 0x79, 0x94
#define RGB_CATPPUCCIN_FRAPPE_SURFACE2 0x62, 0x68, 0x80
#define RGB_CATPPUCCIN_FRAPPE_SURFACE1 0x51, 0x57, 0x6D
#define RGB_CATPPUCCIN_FRAPPE_SURFACE0 0x41, 0x45, 0x59
#define RGB_CATPPUCCIN_FRAPPE_BASE 0x30, 0x34, 0x46
#define RGB_CATPPUCCIN_FRAPPE_MANTLE 0x29, 0x2C, 0x3C
#define RGB_CATPPUCCIN_FRAPPE_CRUST 0x23, 0x26, 0x34
#define RGB_CATPPUCCIN_FRAPPE_ACCENT __CTP_CONCAT(RGB_CATPPUCCIN_FRAPPE_, CATPPUCCIN_ACCENT)
  
#define RGB_CATPPUCCIN_MACCHIATO_ROSEWATER 0xF4, 0xDB, 0xD6
#define RGB_CATPPUCCIN_MACCHIATO_FLAMINGO 0xF0, 0xC6, 0xC6
#define RGB_CATPPUCCIN_MACCHIATO_PINK 0xF5, 0xBD, 0xE6
#define RGB_CATPPUCCIN_MACCHIATO_MAUVE 0xC6, 0xA0, 0xF6
#define RGB_CATPPUCCIN_MACCHIATO_RED 0xED, 0x87, 0x96
#define RGB_CATPPUCCIN_MACCHIATO_MAROON 0xEE, 0x99, 0xA0
#define RGB_CATPPUCCIN_MACCHIATO_PEACH 0xF5, 0xA9, 0x7F
#define RGB_CATPPUCCIN_MACCHIATO_YELLOW 0xEE, 0xD4, 0x9F
#define RGB_CATPPUCCIN_MACCHIATO_GREEN 0xA6, 0xDA, 0x95
#define RGB_CATPPUCCIN_MACCHIATO_TEAL 0x8B, 0xD5, 0xCA
#define RGB_CATPPUCCIN_MACCHIATO_SKY 0x91, 0xD7, 0xE3
#define RGB_CATPPUCCIN_MACCHIATO_SAPPHIRE 0x7D, 0xC4, 0xE4
#define RGB_CATPPUCCIN_MACCHIATO_BLUE 0x8A, 0xAD, 0xF4
#define RGB_CATPPUCCIN_MACCHIATO_LAVENDER 0xB7, 0xBD, 0xF8
#define RGB_CATPPUCCIN_MACCHIATO_TEXT 0xCA, 0xD3, 0xF5
#define RGB_CATPPUCCIN_MACCHIATO_SUBTEXT1 0xB8, 0xC0, 0xE0
#define RGB_CATPPUCCIN_MACCHIATO_SUBTEXT0 0xA5, 0xAD, 0xCB
#define RGB_CATPPUCCIN_MACCHIATO_OVERLAY2 0x93, 0x9A, 0xB7
#define RGB_CATPPUCCIN_MACCHIATO_OVERLAY1 0x80, 0x87, 0xA2
#define RGB_CATPPUCCIN_MACCHIATO_OVERLAY0 0x6E, 0x73, 0x8D
#define RGB_CATPPUCCIN_MACCHIATO_SURFACE2 0x5B, 0x60, 0x78
#define RGB_CATPPUCCIN_MACCHIATO_SURFACE1 0x49, 0x4D, 0x64
#define RGB_CATPPUCCIN_MACCHIATO_SURFACE0 0x36, 0x3A, 0x4F
#define RGB_CATPPUCCIN_MACCHIATO_BASE 0x24, 0x27, 0x3A
#define RGB_CATPPUCCIN_MACCHIATO_MANTLE 0x1E, 0x20, 0x30
#define RGB_CATPPUCCIN_MACCHIATO_CRUST 0x18, 0x19, 0x26
#define RGB_CATPPUCCIN_MACCHIATO_ACCENT __CTP_CONCAT(RGB_CATPPUCCIN_MACCHIATO_, CATPPUCCIN_ACCENT)
  
#define RGB_CATPPUCCIN_MOCHA_ROSEWATER 0xF5, 0xE0, 0xDC
#define RGB_CATPPUCCIN_MOCHA_FLAMINGO 0xF2, 0xCD, 0xCD
#define RGB_CATPPUCCIN_MOCHA_PINK 0xF5, 0xC2, 0xE7
#define RGB_CATPPUCCIN_MOCHA_MAUVE 0xCB, 0xA6, 0xF7
#define RGB_CATPPUCCIN_MOCHA_RED 0xF3, 0x8B, 0xA8
#define RGB_CATPPUCCIN_MOCHA_MAROON 0xEB, 0xA0, 0xAC
#define RGB_CATPPUCCIN_MOCHA_PEACH 0xFA, 0xB3, 0x87
#define RGB_CATPPUCCIN_MOCHA_YELLOW 0xF9, 0xE2, 0xAF
#define RGB_CATPPUCCIN_MOCHA_GREEN 0xA6, 0xE3, 0xA1
#define RGB_CATPPUCCIN_MOCHA_TEAL 0x94, 0xE2, 0xD5
#define RGB_CATPPUCCIN_MOCHA_SKY 0x89, 0xDC, 0xEB
#define RGB_CATPPUCCIN_MOCHA_SAPPHIRE 0x74, 0xC7, 0xEC
#define RGB_CATPPUCCIN_MOCHA_BLUE 0x89, 0xB4, 0xFA
#define RGB_CATPPUCCIN_MOCHA_LAVENDER 0xB4, 0xBE, 0xFE
#define RGB_CATPPUCCIN_MOCHA_TEXT 0xCD, 0xD6, 0xF4
#define RGB_CATPPUCCIN_MOCHA_SUBTEXT1 0xBA, 0xC2, 0xDE
#define RGB_CATPPUCCIN_MOCHA_SUBTEXT0 0xA6, 0xAD, 0xC8
#define RGB_CATPPUCCIN_MOCHA_OVERLAY2 0x93, 0x99, 0xB2
#define RGB_CATPPUCCIN_MOCHA_OVERLAY1 0x7F, 0x84, 0x9C
#define RGB_CATPPUCCIN_MOCHA_OVERLAY0 0x6C, 0x70, 0x86
#define RGB_CATPPUCCIN_MOCHA_SURFACE2 0x58, 0x5B, 0x70
#define RGB_CATPPUCCIN_MOCHA_SURFACE1 0x45, 0x47, 0x5A
#define RGB_CATPPUCCIN_MOCHA_SURFACE0 0x31, 0x32, 0x44
#define RGB_CATPPUCCIN_MOCHA_BASE 0x1E, 0x1E, 0x2E
#define RGB_CATPPUCCIN_MOCHA_MANTLE 0x18, 0x18, 0x25
#define RGB_CATPPUCCIN_MOCHA_CRUST 0x11, 0x11, 0x1B
#define RGB_CATPPUCCIN_MOCHA_ACCENT __CTP_CONCAT(RGB_CATPPUCCIN_MOCHA_, CATPPUCCIN_ACCENT)
    
#define RGB_CATPPUCCIN_ROSEWATER __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _ROSEWATER)
#define RGB_CATPPUCCIN_FLAMINGO __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _FLAMINGO)
#define RGB_CATPPUCCIN_PINK __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _PINK)
#define RGB_CATPPUCCIN_MAUVE __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _MAUVE)
#define RGB_CATPPUCCIN_RED __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _RED)
#define RGB_CATPPUCCIN_MAROON __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _MAROON)
#define RGB_CATPPUCCIN_PEACH __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _PEACH)
#define RGB_CATPPUCCIN_YELLOW __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _YELLOW)
#define RGB_CATPPUCCIN_GREEN __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _GREEN)
#define RGB_CATPPUCCIN_TEAL __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _TEAL)
#define RGB_CATPPUCCIN_SKY __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SKY)
#define RGB_CATPPUCCIN_SAPPHIRE __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SAPPHIRE)
#define RGB_CATPPUCCIN_BLUE __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _BLUE)
#define RGB_CATPPUCCIN_LAVENDER __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _LAVENDER)
#define RGB_CATPPUCCIN_TEXT __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _TEXT)
#define RGB_CATPPUCCIN_SUBTEXT1 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SUBTEXT1)
#define RGB_CATPPUCCIN_SUBTEXT0 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SUBTEXT0)
#define RGB_CATPPUCCIN_OVERLAY2 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _OVERLAY2)
#define RGB_CATPPUCCIN_OVERLAY1 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _OVERLAY1)
#define RGB_CATPPUCCIN_OVERLAY0 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _OVERLAY0)
#define RGB_CATPPUCCIN_SURFACE2 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SURFACE2)
#define RGB_CATPPUCCIN_SURFACE1 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SURFACE1)
#define RGB_CATPPUCCIN_SURFACE0 __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _SURFACE0)
#define RGB_CATPPUCCIN_BASE __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _BASE)
#define RGB_CATPPUCCIN_MANTLE __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _MANTLE)
#define RGB_CATPPUCCIN_CRUST __CTP_CONCAT3(RGB_CATPPUCCIN_, CATPPUCCIN_FLAVOR, _CRUST)
#define RGB_CATPPUCCIN_ACCENT __CTP_CONCAT(RGB_CATPPUCCIN_, CATPPUCCIN_ACCENT)
